/**
 * JICF Wedding Certificate template.
 * Landscape marriage record. No QR element — the certificate id is plain text.
 */

import { CertificateTemplate } from "../types";
import { JICF_COLORS } from "./constants";
import {
  JICF_WEDDING_CERTIFICATE_ID,
  JICF_WEDDING_COVENANT,
} from "@/lib/jicf/wedding-certificate-data";

export const jicfWeddingCertificate: CertificateTemplate = {
  id: "jicf-wedding-certificate",
  name: "Wedding Certificate",
  description:
    "Official Jinan International Christian Fellowship marriage certificate. Landscape record with a printed certificate id and no QR code.",
  organization: "jicf",
  category: "wedding",
  elements: [
    {
      id: "outer-border",
      type: "shape",
      content: "",
      position: { x: 16, y: 16, width: 968, height: 675 },
      style: { color: JICF_COLORS.blue, borderRadius: "8px" },
    },
    {
      id: "inner-border",
      type: "shape",
      content: "",
      position: { x: 32, y: 32, width: 936, height: 643 },
      style: { color: "#fffde7", borderRadius: "4px" },
    },
    {
      id: "church-name",
      type: "text",
      content: "JINAN INTERNATIONAL CHRISTIAN FELLOWSHIP",
      position: { x: 80, y: 52, width: 840, height: 28 },
      style: {
        fontSize: 18,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "church-subtitle",
      type: "text",
      content: "Official Marriage Certification",
      position: { x: 80, y: 84, width: 840, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: "serif",
        fontStyle: "italic",
        color: JICF_COLORS.red,
        textAlign: "center",
      },
    },
    {
      id: "certificate-title",
      type: "text",
      content: "WEDDING CERTIFICATE",
      position: { x: 80, y: 118, width: 840, height: 40 },
      style: {
        fontSize: 32,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "title-underline",
      type: "shape",
      content: "",
      position: { x: 350, y: 162, width: 300, height: 3 },
      style: { color: JICF_COLORS.yellow, borderRadius: "2px" },
    },
    {
      id: "certification",
      type: "text",
      content:
        "This is to certify that on the {{ceremonyDay}} day of {{ceremonyMonth}}, {{ceremonyYear}}, in {{location}}, {{brideName}} and {{groomName}} were united in marriage.",
      position: { x: 90, y: 184, width: 820, height: 48 },
      style: {
        fontSize: 14,
        fontFamily: "serif",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: "1.35",
      },
    },
    {
      id: "bride-label",
      type: "text",
      content: "BRIDE",
      position: { x: 80, y: 248, width: 380, height: 16 },
      style: {
        fontSize: 11,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "bride-name",
      type: "text",
      content: "{{brideName}}",
      position: { x: 70, y: 268, width: 400, height: 36 },
      style: {
        fontSize: 22,
        fontFamily: "serif",
        fontWeight: "bold",
        fontStyle: "italic",
        color: JICF_COLORS.red,
        textAlign: "center",
      },
    },
    {
      id: "and-mark",
      type: "text",
      content: "&",
      position: { x: 470, y: 268, width: 60, height: 36 },
      style: {
        fontSize: 22,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.gold,
        textAlign: "center",
      },
    },
    {
      id: "groom-label",
      type: "text",
      content: "GROOM",
      position: { x: 540, y: 248, width: 380, height: 16 },
      style: {
        fontSize: 11,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "groom-name",
      type: "text",
      content: "{{groomName}}",
      position: { x: 530, y: 268, width: 400, height: 36 },
      style: {
        fontSize: 22,
        fontFamily: "serif",
        fontWeight: "bold",
        fontStyle: "italic",
        color: JICF_COLORS.red,
        textAlign: "center",
      },
    },
    {
      id: "covenant",
      type: "text",
      content: "{{covenantText}}",
      position: { x: 90, y: 320, width: 820, height: 72 },
      style: {
        fontSize: 13,
        fontFamily: "serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: "1.35",
      },
    },
    {
      id: "officiant-heading",
      type: "text",
      content: "OFFICIANT",
      position: { x: 80, y: 408, width: 400, height: 16 },
      style: {
        fontSize: 12,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "officiant-name",
      type: "text",
      content: "{{officiantName}}",
      position: { x: 80, y: 430, width: 400, height: 24 },
      style: {
        fontSize: 16,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "officiant-line",
      type: "shape",
      content: "",
      position: { x: 140, y: 490, width: 280, height: 1 },
      style: { color: JICF_COLORS.blue },
    },
    {
      id: "officiant-sign-label",
      type: "text",
      content: "Signature",
      position: { x: 140, y: 496, width: 280, height: 16 },
      style: {
        fontSize: 11,
        fontFamily: "serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
    {
      id: "witness-heading",
      type: "text",
      content: "WITNESSES",
      position: { x: 520, y: 408, width: 400, height: 16 },
      style: {
        fontSize: 12,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.blue,
        textAlign: "center",
      },
    },
    {
      id: "witness-1-label",
      type: "text",
      content: "Witness 1",
      position: { x: 530, y: 436, width: 180, height: 16 },
      style: {
        fontSize: 12,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.red,
        textAlign: "center",
      },
    },
    {
      id: "witness-1-line",
      type: "shape",
      content: "",
      position: { x: 530, y: 490, width: 180, height: 1 },
      style: { color: JICF_COLORS.blue },
    },
    {
      id: "witness-1-sign",
      type: "text",
      content: "Signature",
      position: { x: 530, y: 496, width: 180, height: 16 },
      style: {
        fontSize: 11,
        fontFamily: "serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
    {
      id: "witness-2-label",
      type: "text",
      content: "Witness 2",
      position: { x: 740, y: 436, width: 180, height: 16 },
      style: {
        fontSize: 12,
        fontFamily: "serif",
        fontWeight: "bold",
        color: JICF_COLORS.red,
        textAlign: "center",
      },
    },
    {
      id: "witness-2-line",
      type: "shape",
      content: "",
      position: { x: 740, y: 490, width: 180, height: 1 },
      style: { color: JICF_COLORS.blue },
    },
    {
      id: "witness-2-sign",
      type: "text",
      content: "Signature",
      position: { x: 740, y: 496, width: 180, height: 16 },
      style: {
        fontSize: 11,
        fontFamily: "serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
    {
      id: "certificate-id",
      type: "text",
      content: `Certificate ID: {{certificateId}}`,
      position: { x: 80, y: 560, width: 840, height: 20 },
      style: {
        fontSize: 12,
        fontFamily: "serif",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
  ],
  pageSettings: {
    width: 1000,
    height: 707,
    margin: { top: 16, right: 16, bottom: 16, left: 16 },
    background: { color: "#fffef8" },
  },
  fonts: [{ family: "serif", variants: ["normal", "bold", "italic"] }],
};

export const JICF_WEDDING_TEMPLATE_FIELDS = {
  certificateId: JICF_WEDDING_CERTIFICATE_ID,
  covenantText: JICF_WEDDING_COVENANT,
};
